n = input("Digite algo:\033[1;32m ")
print("\033[mO tipo primitivo desse valor", type(n))
print("Só tem espaços?", n.isspace())
print("É um número?", n.isnumeric())
print("É alfabético?", n.isalpha())
print("É alfanumérico?", n.isalnum())
print("Está em maiúsculas?", n.isupper())
print("Está em minúsculas?", n.islower())
print("Está capitalizada?", n.istitle())